# Generated by Django 2.2.4 on 2019-10-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(upload_to='static/img', verbose_name='图片'),
        ),
    ]
