# Generated by Django 2.2.4 on 2019-10-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artical', '0002_auto_20191024_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=models.CharField(blank=True, max_length=200, verbose_name='分类描述'),
        ),
    ]
