# Generated by Django 2.2.7 on 2019-11-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artical',
            name='uv',
            field=models.PositiveIntegerField(default=1, verbose_name='浏览量'),
        ),
        migrations.AlterField(
            model_name='artical',
            name='pv',
            field=models.PositiveIntegerField(default=1, verbose_name='点击量'),
        ),
    ]
