# Generated by Django 2.2.4 on 2019-10-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, '正常'), (0, '删除')], default=1, verbose_name='状态')),
                ('img', models.ImageField(upload_to='static/img', verbose_name='个性图片')),
                ('introduction', models.CharField(max_length=300, verbose_name='网站描述')),
                ('category', models.CharField(max_length=15, verbose_name='分类名')),
            ],
            options={
                'verbose_name': '首页部分',
                'verbose_name_plural': '首页部分',
            },
        ),
        migrations.CreateModel(
            name='FriLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, '正常'), (0, '删除')], default=1, verbose_name='状态')),
                ('img', models.ImageField(blank=True, upload_to='static/img', verbose_name='友链图片')),
                ('name', models.CharField(max_length=15, verbose_name='友链名称')),
                ('link', models.URLField(verbose_name='友链链接')),
            ],
            options={
                'verbose_name': '友链部分',
                'verbose_name_plural': '友链部分',
            },
        ),
        migrations.CreateModel(
            name='SiteMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, '正常'), (0, '删除')], default=1, verbose_name='状态')),
                ('pv', models.PositiveIntegerField(default=1)),
                ('follow', models.PositiveIntegerField(default=1)),
                ('total', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': '站长统计部分',
                'verbose_name_plural': '站长统计部分',
            },
        ),
    ]
